on:
  workflow_call:

jobs:
  data-tests:
    runs-on: ubuntu-latest
    env:
      GEO2DGGS_TEST_DATA_DIR: tests/test_data
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Tests involving datasets (much slower)
        run: |
          python -m unittest discover -s tests/data_tests -p '*.py'
          python -m unittest discover -s tests/script_tests -p '*.py'