name: Python package release

# Works only on pushes to the main branch with tags that start with "v"
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-unit-tests:
    uses: ./.github/workflows/ci-reusable-build.yml

  data-tests:
    needs: build-and-unit-tests
    uses: ./.github/workflows/ci-reusable-data-tests.yml

  pack-and-release:
    needs: data-tests
    runs-on: ubuntu-latest
    steps:
      - name: Build package
        # For now, every version is an alpha (i.e., CI produced) version.
        # The base version is an attribute in pyproject.toml
        # To get the incremental numbering after the "a", we use YYYYMMDDHHMM
        run: |
          python setup.py egg_info -b "a`date '+%Y%m%d%H%M'`" bdist_wheel
      - name: Retrieve version
        run: |
          echo "VERSION_TAG=$(find dist -name '*.whl' | awk -F'-' '{ print $2 }')" >> $GITHUB_OUTPUT
        id: version
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          commit: "main"
          tag: v${{ steps.version.outputs.VERSION_TAG }}


