on:
  workflow_call:

jobs:
  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          python -m pip install --upgrade build
          python -m pip install --upgrade wheel
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Unit tests (fast)
        run: |
          python -m unittest discover -s tests/unit_tests -p '*.py'