name: Python package release

# Run only on tag pushes (i.e. git push origin TAG_ID) as long as TAG_ID starts with "0" or "1"
on:
  push:
    tags:
      - 0*
      - 1*

jobs:
  build-and-unit-tests:
    uses: ./.github/workflows/ci-reusable-build.yml

  data-tests:
    needs: build-and-unit-tests
    uses: ./.github/workflows/ci-reusable-data-tests.yml

  pack-and-release:
    needs: data-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          python -m pip install --upgrade build
          python -m pip install --upgrade wheel
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Build package
        run: |        
          python -m build
      - name: Retrieve version
        # The version is an attribute in pyproject.toml (that must be changed after generating the stable version)
        run: |
          echo "VERSION_TAG=$(find dist -name '*.whl' | awk -F'-' '{ print $2 }')" >> $GITHUB_OUTPUT
        id: version
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl,dist/*.gz"


