name: Python package release

# Run only on pushes with commits tagged with anything that starts with "0" or "1"
on:
  push:
    tags:
      - 0*
      - 1*

jobs:
  build-and-unit-tests:
    uses: ./.github/workflows/ci-reusable-build.yml

  data-tests:
    needs: build-and-unit-tests
    uses: ./.github/workflows/ci-reusable-data-tests.yml

  pack-and-release:
    needs: data-tests
    runs-on: ubuntu-latest

    steps:
      - name: Build package
        # The version is an attribute in pyproject.toml (that must be changed after generating the stable version)
        run: |
          python setup.py egg_info bdist_wheel
      - name: Retrieve version
        run: |
          echo "VERSION_TAG=$(find dist -name '*.whl' | awk -F'-' '{ print $2 }')" >> $GITHUB_OUTPUT
        id: version
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"


