name: Python build and test

on: [push]

jobs:
  build-and-unit-tests:
    uses: ./.github/workflows/ci-reusable-build.yml

  data-tests:
    needs: build-and-unit-tests
    uses: ./.github/workflows/ci-reusable-data-tests.yml
