name: Python build and test

# Run this on push to branches, but not on push to tags
on:
  push:
    branches:
      - '**'

jobs:
  build-and-unit-tests:
    uses: ./.github/workflows/ci-reusable-build.yml

  data-tests:
    needs: build-and-unit-tests
    uses: ./.github/workflows/ci-reusable-data-tests.yml

  pack-and-release:
    needs: data-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          python -m pip install --upgrade build
          python -m pip install --upgrade wheel
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Build package (alpha version)
        # The base version is an attribute in pyproject.toml
        # To get the incremental numbering after the "a", we use YYYYMMDDHHMM
        # We change the version in pyproject.toml to include the aDATE, so the generated packages
        # have that version and not only the base version
        run: |
          export DATE=`date '+%Y%m%d%H%M'`
          sed -i -r 's/version = "([0-9]+(\.[0-9]+)*)"/version = "\1a'"$DATE"'"/' pyproject.toml
          python -m build
      - name: Set alpha version tag
        run: |                
          echo "VERSION_TAG=$(find dist -name '*.whl' | awk -F'-' '{ print $2 }')" >> $GITHUB_OUTPUT
        id: version
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl,dist/*.gz"
          commit: "main"
          tag: v${{ steps.version.outputs.VERSION_TAG }}
